FROM golang:1.14.3
#FROM python:3.9.16-alpine3.16
FROM python:3.9

RUN apt-get update && apt-get install ffmpeg -y

WORKDIR /code

COPY ./r.txt /code/r.txt

# RUN apk update && apk add git

RUN pip3 install -r /code/r.txt

COPY ./app /code/app

COPY ./.env /code/.env

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
